#pragma once

#define ECC_PROJECTILE ECC_GameTraceChannel1
#define ECC_PESTILENCE_CHARACTER ECC_GameTraceChannel2
#define ECC_INTERACTABLE ECC_GameTraceChannel3
#define ECC_PULSEVISION ECC_GameTraceChannel4
#define ECC_PULSEWALL ECC_GameTraceChannel5
#define ECC_NOTELEPORT ECC_GameTraceChannel6
#define ECC_STREAMINGVOLUME ECC_GameTraceChannel7
